meta_product_name: "Notifa.app"
meta_title: "Notifa.app - Be the first to know"
meta_description: "Looking for an apartment, room or house?
Notifa contacts you as soon as a rental listing is uploaded
anywhere online so you are always the first one to know."
meta_image: "home_banner_2.png" # should exist in `app/assets/images/`
